baseURL = 'http://stouffersolutions.com/'
languageCode = 'en-us'
title = 'Stouffer Solutions'

[params]
    description = "Business solutions that learn from you"

[[module.imports]]
  path = "github.com/syui/hugo-theme-air"